/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
        //Search_Amazon search= new Search_Amazon();
        //TODO: call your test case functions one after other here
        //BookMyShow shows = new BookMyShow();
       // Post_Linkedin post= new Post_Linkedin();
      // Automate_Nested_Frames frames= new Automate_Nested_Frames();
      Automate_Windows_Handle windows = new Automate_Windows_Handle();
        //tests.testCase01();
        //search.searchamazon();
       // shows.bookmyshow();
       //post.postlinkedin();
    // frames.automatenestedframes();
    //imdb.automateimdb();
    windows.automatewindowshandle();
        //END Tests

        //search.endTest();
        //shows.endTest();
        //post.endTest();
        //frames.endTest();
        //imdb.endTest();
        windows.endTest();
       // tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
